/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;
import Classes.ModuloConexao;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author MAGALU
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Connection conexao = null;
    
    public TelaPrincipal() {
  
        initComponents();
        this.setExtendedState(TelaPrincipal.MAXIMIZED_BOTH);
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        lblData = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ClienteMenuPrincipal = new javax.swing.JMenu();
        ClienteSubMenu = new javax.swing.JMenuItem();
        OrdemServicoSubMenu = new javax.swing.JMenuItem();
        UsuarioSubMenu = new javax.swing.JMenuItem();
        RelatoriosMenuPrincipal = new javax.swing.JMenu();
        ServiçosSubMenu = new javax.swing.JMenuItem();
        ClienteRelatorioSubMenu = new javax.swing.JMenuItem();
        AjudaMenuPrincipal = new javax.swing.JMenu();
        SobreSubMenu = new javax.swing.JMenuItem();
        OpcoesMenuPrincipal = new javax.swing.JMenu();
        SairSubMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Painel de controle");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblData.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        lblData.setText("Data");

        lblUser.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblUser.setText("Usuário");

        ClienteMenuPrincipal.setText("Cliente");

        ClienteSubMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        ClienteSubMenu.setText("Cliente");
        ClienteSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteSubMenuActionPerformed(evt);
            }
        });
        ClienteMenuPrincipal.add(ClienteSubMenu);

        OrdemServicoSubMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OrdemServicoSubMenu.setText("Ordem de serviço");
        OrdemServicoSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdemServicoSubMenuActionPerformed(evt);
            }
        });
        ClienteMenuPrincipal.add(OrdemServicoSubMenu);

        UsuarioSubMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        UsuarioSubMenu.setText("Usuário");
        UsuarioSubMenu.setEnabled(false);
        UsuarioSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioSubMenuActionPerformed(evt);
            }
        });
        ClienteMenuPrincipal.add(UsuarioSubMenu);

        jMenuBar1.add(ClienteMenuPrincipal);

        RelatoriosMenuPrincipal.setText("Relatórios");
        RelatoriosMenuPrincipal.setEnabled(false);

        ServiçosSubMenu.setText("Serviços");
        ServiçosSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiçosSubMenuActionPerformed(evt);
            }
        });
        RelatoriosMenuPrincipal.add(ServiçosSubMenu);

        ClienteRelatorioSubMenu.setText("Clientes");
        ClienteRelatorioSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteRelatorioSubMenuActionPerformed(evt);
            }
        });
        RelatoriosMenuPrincipal.add(ClienteRelatorioSubMenu);

        jMenuBar1.add(RelatoriosMenuPrincipal);

        AjudaMenuPrincipal.setText("Ajuda");

        SobreSubMenu.setText("Sobre");
        SobreSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreSubMenuActionPerformed(evt);
            }
        });
        AjudaMenuPrincipal.add(SobreSubMenu);

        jMenuBar1.add(AjudaMenuPrincipal);

        OpcoesMenuPrincipal.setText("Opções");
        OpcoesMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcoesMenuPrincipalActionPerformed(evt);
            }
        });

        SairSubMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        SairSubMenu.setText("Sair");
        SairSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairSubMenuActionPerformed(evt);
            }
        });
        OpcoesMenuPrincipal.add(SairSubMenu);

        jMenuBar1.add(OpcoesMenuPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblData)
                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblData)
                .addGap(103, 463, Short.MAX_VALUE))
            .addComponent(desktop)
        );

        setSize(new java.awt.Dimension(1380, 718));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    

    
    private void ClienteSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteSubMenuActionPerformed
        // TODO add your handling code here:
        TelaCliente tela = new TelaCliente();
        
        tela.setVisible(true);
        
        desktop.add(tela);
 
    }//GEN-LAST:event_ClienteSubMenuActionPerformed

    private void UsuarioSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioSubMenuActionPerformed
        TelaUsuario tela = new TelaUsuario();
        tela.setVisible(true);
        desktop.add(tela);
       
        
    }//GEN-LAST:event_UsuarioSubMenuActionPerformed

    private void SairSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairSubMenuActionPerformed
       int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?","ATENÇÃO",JOptionPane.YES_NO_OPTION);
        System.out.println(sair); //yes 0 no 1
        if(sair == 0){
        System.exit(0);
        }
    }//GEN-LAST:event_SairSubMenuActionPerformed

    private void OpcoesMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcoesMenuPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcoesMenuPrincipalActionPerformed

    private void SobreSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreSubMenuActionPerformed
        Sobre sobre = new Sobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_SobreSubMenuActionPerformed

    private void OrdemServicoSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdemServicoSubMenuActionPerformed
        TelaOS OS = new TelaOS();
        OS.setVisible(true);
        desktop.add(OS);
        
        
    }//GEN-LAST:event_OrdemServicoSubMenuActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date data = new Date();
       
        DateFormat formatar = DateFormat.getDateInstance(DateFormat.SHORT);
        
        lblData.setText(formatar.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void ClienteRelatorioSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteRelatorioSubMenuActionPerformed
        int confirmar = JOptionPane.showConfirmDialog(null , "Deseja realizar a impressão desse relatório?","ATENÇÃO",JOptionPane.YES_NO_OPTION);
        
        if(confirmar == JOptionPane.YES_OPTION){
        
        try{
        
            JasperPrint print = JasperFillManager.fillReport("D:\\ireport\\clientes.jasper",null,conexao);
            
            JasperViewer.viewReport(print,false);
        
        }catch(Exception e){
        
        
        JOptionPane.showMessageDialog(null, e);
        
        }
        
        }
    }//GEN-LAST:event_ClienteRelatorioSubMenuActionPerformed

    private void ServiçosSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiçosSubMenuActionPerformed
       int confirmar = JOptionPane.showConfirmDialog(null , "Deseja realizar a impressão desse relatório?","ATENÇÃO",JOptionPane.YES_NO_OPTION);
        
        if(confirmar == JOptionPane.YES_OPTION){
        
        try{
        
            JasperPrint print = JasperFillManager.fillReport("D:\\ireport\\servicosTB.jasper",null,conexao);
            
            JasperViewer.viewReport(print,false);
        
        }catch(Exception e){
        
        
        JOptionPane.showMessageDialog(null, e);
        
        }
        
        }
    }//GEN-LAST:event_ServiçosSubMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AjudaMenuPrincipal;
    private javax.swing.JMenu ClienteMenuPrincipal;
    private javax.swing.JMenuItem ClienteRelatorioSubMenu;
    private javax.swing.JMenuItem ClienteSubMenu;
    private javax.swing.JMenu OpcoesMenuPrincipal;
    private javax.swing.JMenuItem OrdemServicoSubMenu;
    public static javax.swing.JMenu RelatoriosMenuPrincipal;
    private javax.swing.JMenuItem SairSubMenu;
    private javax.swing.JMenuItem ServiçosSubMenu;
    private javax.swing.JMenuItem SobreSubMenu;
    public static javax.swing.JMenuItem UsuarioSubMenu;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
